# Generated by Django 2.2.5 on 2019-09-19 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_publised',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 19, 11, 51, 39, 776062), verbose_name='date published'),
        ),
    ]
