# Generated by Django 2.2.5 on 2019-09-20 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190919_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(default='Important', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_publised',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 22, 15, 29, 971847), verbose_name='date published'),
        ),
    ]
