# Generated by Django 2.2.5 on 2019-09-20 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190920_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='priority',
            field=models.CharField(default='Incomplete', max_length=200),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_publised',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 20, 22, 52, 35, 240804), verbose_name='date published'),
        ),
    ]
